const gwList = [{question :"a band-aid", complement :"n"},
{question :"to repel", complement :"v"},
{question :"to shrink", complement :"v"},
{question :"to screw", complement :"v"},
{question :"to pour", complement :"v"},
{question :"to thrive", complement :"v"},
{question :"get worse", complement :"expr"},
{question :"clumsy", complement :"adj", def:"Awkward in movement or in handling things", ex:"That's the third glass you've smashed this week - you're so clumsy!"},
{question :"to starve", complement :"v"},
{question :"a gambler ", complement :"n"},
{question :"conspicuous", complement :"adj"},
{question :"too close to call", complement :"expr"},
{question :"a shortcoming", complement :"n"},
{question :"to shun", complement :"v"},
{question :"a backlash", complement :"n"},
{question :"From craddle to grave", complement :"expr"},
{question :"unintentionnally", complement :"adv"},
{question :"bittersweet", complement :"adj", bonus:true},
{question :"to shoulder", complement :"v"},
{question :"to pull the plug", complement :"expr"},
{question :"a census", complement :"n", def:"An official count or survey, especially of a population", ex:"We have a census in this country every ten years."},
{question :"There is nothing to write home about", complement :"expr", def:"Not exciting or special"},
{question :"gambling", complement :"n", def:"The activity of betting money, for example in a game or on a horse race", ex:"After his wife died, Kyle got into gambling and lost all of his money."},
{question :"red tape", complement :"expr", def:"paper work, official rules and processes that seem unnecessary and delay results", ex:"Rescue work is often hampered by red tape at national borders."},
{question :"The more, the merrier", complement :"expr", def:"Used to say an occasion will be more enjoyable if a lot of people are there", ex:"Do you mind if I bring a couple of friends to your party? Not at all - the more the merrier!"},
{question :"The bread and butter", complement :"of sb", def:"The activity of betting money, for example in a game or on a horse race", ex:"After his wife died, Kyle got into gambling and lost all of his money."}
];

export default gwList
